/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "matrixOp.h"

bool_t
xdr_Matrix (XDR *xdrs, Matrix *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->rows))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cols))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->data, sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_MatrixPair (XDR *xdrs, MatrixPair *objp)
{
	register int32_t *buf;

	 if (!xdr_Matrix (xdrs, &objp->matrix1))
		 return FALSE;
	 if (!xdr_Matrix (xdrs, &objp->matrix2))
		 return FALSE;
	return TRUE;
}
