/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "matrixOp.h"

Matrix *
matrix_add_1_svc(MatrixPair *argp, struct svc_req *rqstp)
{
	static Matrix  result;

	/*
	 * insert server code here
	 */

	return &result;
}

Matrix *
matrix_mul_1_svc(MatrixPair *argp, struct svc_req *rqstp)
{
	static Matrix  result;

	/*
	 * insert server code here
	 */

	return &result;
}

Matrix *
matrix_inverse_1_svc(Matrix *argp, struct svc_req *rqstp)
{
	static Matrix  result;

	/*
	 * insert server code here
	 */

	return &result;
}

Matrix *
matrix_transpose_1_svc(Matrix *argp, struct svc_req *rqstp)
{
	static Matrix  result;

	/*
	 * insert server code here
	 */

	return &result;
}
