/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "matrixOp.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

Matrix *
matrix_add_1(MatrixPair *argp, CLIENT *clnt)
{
	static Matrix clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, matrix_add,
		(xdrproc_t) xdr_MatrixPair, (caddr_t) argp,
		(xdrproc_t) xdr_Matrix, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Matrix *
matrix_mul_1(MatrixPair *argp, CLIENT *clnt)
{
	static Matrix clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, matrix_mul,
		(xdrproc_t) xdr_MatrixPair, (caddr_t) argp,
		(xdrproc_t) xdr_Matrix, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Matrix *
matrix_inverse_1(Matrix *argp, CLIENT *clnt)
{
	static Matrix clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, matrix_inverse,
		(xdrproc_t) xdr_Matrix, (caddr_t) argp,
		(xdrproc_t) xdr_Matrix, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Matrix *
matrix_transpose_1(Matrix *argp, CLIENT *clnt)
{
	static Matrix clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, matrix_transpose,
		(xdrproc_t) xdr_Matrix, (caddr_t) argp,
		(xdrproc_t) xdr_Matrix, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
