/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MATRIXOP_H_RPCGEN
#define _MATRIXOP_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Matrix {
	int rows;
	int cols;
	double data[100];
};
typedef struct Matrix Matrix;

struct MatrixPair {
	Matrix matrix1;
	Matrix matrix2;
};
typedef struct MatrixPair MatrixPair;

#define MATRIX_PROG 0x31230000
#define MATRIX_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define matrix_add 1
extern  Matrix * matrix_add_1(MatrixPair *, CLIENT *);
extern  Matrix * matrix_add_1_svc(MatrixPair *, struct svc_req *);
#define matrix_mul 2
extern  Matrix * matrix_mul_1(MatrixPair *, CLIENT *);
extern  Matrix * matrix_mul_1_svc(MatrixPair *, struct svc_req *);
#define matrix_inverse 3
extern  Matrix * matrix_inverse_1(Matrix *, CLIENT *);
extern  Matrix * matrix_inverse_1_svc(Matrix *, struct svc_req *);
#define matrix_transpose 4
extern  Matrix * matrix_transpose_1(Matrix *, CLIENT *);
extern  Matrix * matrix_transpose_1_svc(Matrix *, struct svc_req *);
extern int matrix_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define matrix_add 1
extern  Matrix * matrix_add_1();
extern  Matrix * matrix_add_1_svc();
#define matrix_mul 2
extern  Matrix * matrix_mul_1();
extern  Matrix * matrix_mul_1_svc();
#define matrix_inverse 3
extern  Matrix * matrix_inverse_1();
extern  Matrix * matrix_inverse_1_svc();
#define matrix_transpose 4
extern  Matrix * matrix_transpose_1();
extern  Matrix * matrix_transpose_1_svc();
extern int matrix_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Matrix (XDR *, Matrix*);
extern  bool_t xdr_MatrixPair (XDR *, MatrixPair*);

#else /* K&R C */
extern bool_t xdr_Matrix ();
extern bool_t xdr_MatrixPair ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MATRIXOP_H_RPCGEN */
