CC = gcc
CFLAGS = -Wall
LDFLAGS = -lws2_32

# Rules for Testing the Multi Client-Server System

### Test 1
client1_test_1: client_test_1.c
	$(CC) $(CFLAGS) -o client1_test_1 client_test_1.c $(LDFLAGS)

run_client1_test_1: client1_test_1
	./client1_test_1

client2_test_1: client_test_1.c
	$(CC) $(CFLAGS) -o client2_test_1 client_test_1.c $(LDFLAGS)

run_client2_test_1: client2_test_1
	./client2_test_1

client3_test_1: client_test_1.c
	$(CC) $(CFLAGS) -o client3_test_1 client_test_1.c $(LDFLAGS)

run_client3_test_1: client3_test_1
	./client3_test_1

### Test 2
client1_test_2: client_test_2.c
	$(CC) $(CFLAGS) -o client1_test_2 client_test_2.c $(LDFLAGS)

run_client1_test_2: client1_test_2
	./client1_test_2

client2_test_2: client_test_2.c
	$(CC) $(CFLAGS) -o client2_test_2 client_test_2.c $(LDFLAGS)

run_client2_test_2: client2_test_2
	./client2_test_2

client3_test_2: client_test_2.c
	$(CC) $(CFLAGS) -o client3_test_2 client_test_2.c $(LDFLAGS)

run_client3_test_2: client3_test_2
	./client3_test_2

### Test 3
client1_test_3: client_test_3.c
	$(CC) $(CFLAGS) -o client1_test_3 client_test_3.c $(LDFLAGS)

run_client1_test_3: client1_test_3
	./client1_test_3

client2_test_3: client_test_3.c
	$(CC) $(CFLAGS) -o client2_test_3 client_test_3.c $(LDFLAGS)

run_client2_test_3: client2_test_3
	./client2_test_3

client3_test_3: client_test_3.c
	$(CC) $(CFLAGS) -o client3_test_3 client_test_3.c $(LDFLAGS)

run_client3_test_3: client3_test_3
	./client3_test_3